# Generated by Django 5.0.3 on 2024-03-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
