# Generated by Django 5.0.3 on 2024-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0005_remove_customuser_dealer_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.BooleanField(default=True),
        ),
    ]
