# Generated by Django 5.0.3 on 2024-03-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0007_customuser_dealer_alter_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
