# Generated by Django 5.0.3 on 2024-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0008_customdealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDealer',
        ),
    ]
