# Generated by Django 5.0.3 on 2024-03-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reg_app', '0011_rename_user_customuserdealer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserDealer',
            new_name='CustomUser',
        ),
    ]
