# Generated by Django 5.0.3 on 2024-03-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0012_rename_customuserdealer_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.IntegerField(),
        ),
    ]
