# Generated by Django 5.0.3 on 2024-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0013_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
