# Generated by Django 5.0.3 on 2024-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0014_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.IntegerField(),
        ),
    ]
