# Generated by Django 5.0.3 on 2024-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0016_customuser_role_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer')], max_length=100),
        ),
    ]
