# Generated by Django 5.0.3 on 2024-03-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
