# Generated by Django 5.0.3 on 2024-04-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0020_alter_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
