# Generated by Django 5.0.3 on 2024-04-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0022_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
