# Generated by Django 5.0.3 on 2024-04-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0032_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
