# Generated by Django 5.0.3 on 2024-04-04 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0033_remove_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg_app.product'),
        ),
    ]
