# Generated by Django 5.0.3 on 2024-04-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0037_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='username',
            new_name='name',
        ),
    ]
