# Generated by Django 5.0.3 on 2024-04-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0038_admin_password_alter_admin_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='username',
        ),
    ]
