# Generated by Django 5.0.3 on 2024-04-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0038_rename_username_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='username',
        ),
    ]
