# Generated by Django 5.0.3 on 2024-04-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0042_customuser_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
