# Generated by Django 5.0.3 on 2024-04-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0043_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
