# Generated by Django 5.0.3 on 2024-04-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0044_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
