# Generated by Django 5.0.3 on 2024-04-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0048_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
