# Generated by Django 5.0.3 on 2024-04-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0049_customuser_city_customuser_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
