# Generated by Django 5.0.3 on 2024-04-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0053_customuser_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dropdown',
        ),
    ]
